CREATE TABLE `pipeline_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pipelineType` enum('video','static') NOT NULL,
	`status` enum('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
	`product` varchar(64) NOT NULL,
	`priority` enum('Low','Medium','High','Urgent') NOT NULL DEFAULT 'Medium',
	`triggerSource` varchar(64) NOT NULL DEFAULT 'manual',
	`foreplayAdId` varchar(256),
	`foreplayAdTitle` text,
	`foreplayAdBrand` text,
	`videoUrl` text,
	`thumbnailUrl` text,
	`transcript` text,
	`visualAnalysis` text,
	`scriptsJson` json,
	`clickupTasksJson` json,
	`staticAdImages` json,
	`staticAnalysis` text,
	`generatedImageUrl` text,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `pipeline_runs_id` PRIMARY KEY(`id`)
);
