/**
 * Product Compositor — Two-Pass Image Compositing
 * 
 * Solves the AI label accuracy problem by:
 * 1. Generating background/scene with Gemini (no product in the image)
 * 2. Compositing the real product render PNG on top using sharp
 * 
 * This guarantees pixel-perfect product labels because the actual
 * uploaded product render is used, not an AI approximation.
 */

import sharp from "sharp";
import axios from "axios";
import { storagePut } from "../storage";

// ============================================================
// TYPES
// ============================================================

export interface CompositeOptions {
  /** The AI-generated background image URL (no product in it) */
  backgroundUrl: string;
  /** The real product render PNG URL (with transparent background) */
  productRenderUrl: string;
  /** Where to place the product: "center", "left", "right", "bottom-center" */
  productPosition?: ProductPosition;
  /** Product size as percentage of canvas width (0.2 = 20%, 0.5 = 50%) */
  productScale?: number;
  /** Vertical offset from the calculated position (negative = up, positive = down) */
  verticalOffset?: number;
  /** Optional drop shadow behind the product */
  addShadow?: boolean;
  /** Optional glow effect around the product */
  addGlow?: boolean;
  /** Glow colour in hex (default: based on product) */
  glowColor?: string;
}

export type ProductPosition = "center" | "left" | "right" | "bottom-center" | "bottom-left" | "bottom-right";

export interface CompositeResult {
  imageUrl: string;
  s3Key: string;
  width: number;
  height: number;
}

// ============================================================
// FETCH HELPER
// ============================================================

async function fetchImageBuffer(url: string): Promise<Buffer> {
  const response = await axios.get(url, {
    responseType: "arraybuffer",
    timeout: 30000,
    headers: { "User-Agent": "Mozilla/5.0" },
  });
  return Buffer.from(response.data);
}

// ============================================================
// MAIN COMPOSITOR
// ============================================================

/**
 * Composite a real product render onto an AI-generated background.
 * 
 * The product render should be a PNG with transparent background.
 * The background should be a full scene generated by Gemini WITHOUT
 * any product in it.
 */
export async function compositeProductOnBackground(
  options: CompositeOptions
): Promise<CompositeResult> {
  const {
    backgroundUrl,
    productRenderUrl,
    productPosition = "center",
    productScale = 0.45,
    verticalOffset = 0,
    addShadow = false,
    addGlow = false,
    glowColor = "#00ff88",
  } = options;

  console.log("[Compositor] Starting two-pass compositing...");
  console.log(`[Compositor] Background: ${backgroundUrl}`);
  console.log(`[Compositor] Product render: ${productRenderUrl}`);
  console.log(`[Compositor] Position: ${productPosition}, Scale: ${productScale}`);

  // Step 1: Fetch both images
  const [bgBuffer, productBuffer] = await Promise.all([
    fetchImageBuffer(backgroundUrl),
    fetchImageBuffer(productRenderUrl),
  ]);

  // Step 2: Get background dimensions
  const bgMeta = await sharp(bgBuffer).metadata();
  const bgWidth = bgMeta.width || 1024;
  const bgHeight = bgMeta.height || 1024;
  console.log(`[Compositor] Background size: ${bgWidth}x${bgHeight}`);

  // Step 3: Resize product render to target scale
  const targetProductWidth = Math.round(bgWidth * productScale);
  const resizedProduct = await sharp(productBuffer)
    .resize({ width: targetProductWidth, fit: "inside" })
    .ensureAlpha()
    .toBuffer();

  const productMeta = await sharp(resizedProduct).metadata();
  const productWidth = productMeta.width || targetProductWidth;
  const productHeight = productMeta.height || targetProductWidth;
  console.log(`[Compositor] Product resized to: ${productWidth}x${productHeight}`);

  // Step 4: Calculate position
  const { left, top } = calculatePosition(
    bgWidth, bgHeight,
    productWidth, productHeight,
    productPosition,
    verticalOffset
  );
  console.log(`[Compositor] Product position: left=${left}, top=${top}`);

  // Step 5: Build composite layers
  const layers: sharp.OverlayOptions[] = [];

  // Optional: Add drop shadow behind the product
  if (addShadow) {
    const shadowBuffer = await createDropShadow(resizedProduct, productWidth, productHeight);
    layers.push({
      input: shadowBuffer,
      left: Math.max(0, left + 8),
      top: Math.max(0, top + 8),
      blend: "over" as const,
    });
  }

  // Optional: Add glow effect
  if (addGlow) {
    const glowBuffer = await createGlowEffect(resizedProduct, productWidth, productHeight, glowColor);
    layers.push({
      input: glowBuffer,
      left: Math.max(0, left - 10),
      top: Math.max(0, top - 10),
      blend: "over" as const,
    });
  }

  // Add the actual product render
  layers.push({
    input: resizedProduct,
    left: Math.max(0, left),
    top: Math.max(0, top),
    blend: "over" as const,
  });

  // Step 6: Composite all layers onto the background
  const composited = await sharp(bgBuffer)
    .composite(layers)
    .png({ quality: 95 })
    .toBuffer();

  console.log(`[Compositor] Compositing complete. Output size: ${composited.length} bytes`);

  // Step 7: Upload to S3
  const timestamp = Date.now();
  const randomSuffix = Math.random().toString(36).substring(2, 8);
  const s3Key = `composited-ads/${timestamp}-${randomSuffix}.png`;
  const { url: imageUrl } = await storagePut(s3Key, composited, "image/png");

  console.log(`[Compositor] Uploaded to S3: ${imageUrl}`);

  return {
    imageUrl,
    s3Key,
    width: bgWidth,
    height: bgHeight,
  };
}

// ============================================================
// POSITION CALCULATOR
// ============================================================

function calculatePosition(
  bgWidth: number, bgHeight: number,
  productWidth: number, productHeight: number,
  position: ProductPosition,
  verticalOffset: number
): { left: number; top: number } {
  let left: number;
  let top: number;

  switch (position) {
    case "center":
      left = Math.round((bgWidth - productWidth) / 2);
      top = Math.round((bgHeight - productHeight) / 2);
      break;
    case "left":
      left = Math.round(bgWidth * 0.08);
      top = Math.round((bgHeight - productHeight) / 2);
      break;
    case "right":
      left = Math.round(bgWidth * 0.92 - productWidth);
      top = Math.round((bgHeight - productHeight) / 2);
      break;
    case "bottom-center":
      left = Math.round((bgWidth - productWidth) / 2);
      top = Math.round(bgHeight * 0.95 - productHeight);
      break;
    case "bottom-left":
      left = Math.round(bgWidth * 0.08);
      top = Math.round(bgHeight * 0.95 - productHeight);
      break;
    case "bottom-right":
      left = Math.round(bgWidth * 0.92 - productWidth);
      top = Math.round(bgHeight * 0.95 - productHeight);
      break;
    default:
      left = Math.round((bgWidth - productWidth) / 2);
      top = Math.round((bgHeight - productHeight) / 2);
  }

  // Apply vertical offset
  top += verticalOffset;

  // Clamp to canvas bounds
  left = Math.max(0, Math.min(left, bgWidth - productWidth));
  top = Math.max(0, Math.min(top, bgHeight - productHeight));

  return { left, top };
}

// ============================================================
// EFFECTS
// ============================================================

/**
 * Create a soft drop shadow from the product silhouette.
 * Produces a proper RGBA buffer so Sharp composites it correctly without a black box.
 */
async function createDropShadow(
  productBuffer: Buffer,
  width: number,
  height: number
): Promise<Buffer> {
  // Extract the alpha channel as a greyscale mask
  const alphaMask = await sharp(productBuffer)
    .resize(width, height)
    .ensureAlpha()
    .extractChannel(3)
    .blur(14)
    .toBuffer();

  // Build a black RGBA image the same size, using the blurred alpha mask as opacity
  // This produces a proper RGBA shadow buffer that Sharp can composite correctly
  const blackLayer = await sharp({
    create: {
      width,
      height,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .png()
    .toBuffer();

  // Composite the alpha mask onto the black layer to produce a dark semi-transparent shadow
  return sharp(blackLayer)
    .composite([{ input: alphaMask, blend: 'dest-in' }])
    .modulate({ brightness: 0.4 })
    .png()
    .toBuffer();
}

/**
 * Create a glow effect around the product silhouette.
 */
async function createGlowEffect(
  productBuffer: Buffer,
  width: number,
  height: number,
  color: string
): Promise<Buffer> {
  // Parse hex colour
  const r = parseInt(color.slice(1, 3), 16);
  const g = parseInt(color.slice(3, 5), 16);
  const b = parseInt(color.slice(5, 7), 16);

  // Create a slightly larger canvas for the glow
  const glowWidth = width + 20;
  const glowHeight = height + 20;

  // Extract alpha, tint with glow colour, blur heavily
  const alphaGlow = await sharp(productBuffer)
    .resize(width, height)
    .ensureAlpha()
    .extractChannel(3)
    .toColourspace("b-w")
    .tint({ r, g, b })
    .blur(20)
    .extend({
      top: 10, bottom: 10, left: 10, right: 10,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .toBuffer();

  return alphaGlow;
}

// ============================================================
// BACKGROUND-ONLY PROMPT BUILDER
// ============================================================

/**
 * Build a Gemini prompt that generates ONLY the background scene
 * without any product in it. This is the first pass of the two-pass
 * compositing approach.
 */
export function buildBackgroundOnlyPrompt(options: {
  headline: string;
  subheadline?: string;
  productName: string;
  backgroundStyleDescription: string;
  aspectRatio?: string;
  targetAudience?: string;
  productPosition?: ProductPosition;
}): string {
  const {
    headline,
    subheadline,
    productName,
    backgroundStyleDescription,
    aspectRatio = "1:1",
    productPosition = "center",
  } = options;

  // Describe where to leave space for the product
  const spaceDescription = getSpaceDescription(productPosition);

  return `You are creating a premium supplement advertisement BACKGROUND for paid social media advertising (Meta/TikTok).

CRITICAL INSTRUCTION: Do NOT include any product bottle, container, jar, or supplement packaging in this image. You are generating ONLY the background scene. The real product will be composited on top later.

=== COPY TO RENDER ===
Headline: "${headline}"${subheadline ? `\nSubheadline: "${subheadline}"` : ''}

TEXT RENDERING — CRITICAL (if the text is blurry, soft, thin, or illegible, the image has failed):

HEADLINE RULES (non-negotiable):
- Font weight: 900 weight / ultra-bold / black weight / heavy — NOT regular, NOT medium, NOT light
- Case: UPPERCASE always — every letter capitalised
- Size: Large and dominant — top 30–35% of the frame
- Edge quality: Hard pixel-sharp edges — zero blur, zero feathering
- Contrast: Maximum contrast — white on dark, dark on light — NEVER grey on grey
- Two-colour treatment: If the reference uses two colours (e.g. white + orange accent), replicate that split
- Placement: Top-aligned, fully inside canvas with 5% padding from all edges

SUBHEADLINE (if provided):
- Size: 40–50% of headline font size, regular weight (400), sentence case
- Placed directly below headline, tight spacing

ALL TEXT must be fully inside the canvas — never clipped or cut off at any edge.

=== BACKGROUND & ATMOSPHERE ===
${backgroundStyleDescription}

The background should:
- Create dramatic, premium atmosphere
- Use cinematic lighting and depth
- Feel like a high-budget supplement advertisement
- Fill the ENTIRE canvas edge-to-edge with the scene — no empty patches, no dark voids, no placeholder areas
- The centre of the image should have slightly softer/less busy detail so the product composited on top reads clearly

=== COMPOSITION ===
- Aspect ratio: ${aspectRatio}
- Fill the ENTIRE canvas — the product will be composited on top, so the background must be complete
- ${spaceDescription}
- The centre area should have subtle, less-busy detail (e.g. soft light, gradient, atmospheric haze) so the product stands out when placed there
- Ensure the headline text is in the top third and does NOT overlap with the centre of the image
- Create visual flow that draws the eye from headline down toward the centre product area

=== CRITICAL RULES ===
✗ Do NOT include any product bottle, jar, container, or supplement packaging
✗ Do NOT include any placeholder or silhouette for the product
✗ Do NOT include any ONEST branding or logos (these are on the product)
✓ DO include the headline text rendered beautifully
✓ DO create a dramatic, atmospheric background
✓ DO leave clear space for the product to be added later
✓ DO make it look like a premium paid social ad background

=== QUALITY STANDARDS ===
- Production quality: cinematic, premium, professional
- This should look like it belongs in a high-converting Meta ad
- The background alone should be visually striking and scroll-stopping
- Lighting should create depth and drama`;
}

/**
 * Get a description of where to leave space for the product.
 */
function getSpaceDescription(position: ProductPosition): string {
  switch (position) {
    case "center":
      return "Leave the centre of the image clear and unobstructed for the product";
    case "left":
      return "Leave the left side of the image clear and unobstructed for the product";
    case "right":
      return "Leave the right side of the image clear and unobstructed for the product";
    case "bottom-center":
      return "Leave the bottom-centre area clear and unobstructed for the product";
    case "bottom-left":
      return "Leave the bottom-left area clear and unobstructed for the product";
    case "bottom-right":
      return "Leave the bottom-right area clear and unobstructed for the product";
    default:
      return "Leave the centre of the image clear and unobstructed for the product";
  }
}
